// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://laxvvaepkehdztqehvgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxheHZ2YWVwa2VoZHp0cWVodmdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3OTUyNTMsImV4cCI6MjA2MzM3MTI1M30._h16eIRpvqR37lyh9Xcfh22ZCwMsodvayNevqvOE6ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);